services:
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${rds_mysql_secret}
      MYSQL_DATABASE: meettify
      MYSQL_USER: ${rds_mysql_name}
      MYSQL_PASSWORD: ${rds_mysql_secret}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:8.2.2
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    restart: always

  k6:
    image: grafana/k6:0.35.0
    platform: linux/amd64
    command: ["run", "/test/script.js"]
    restart: always

api:
  build:
    context: .
    dockerfile: docker/api/Dockerfile
    image: zxzz8014/meettify:latest
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OAUTH2_CLIENT_ID=${OAUTH2_CLIENT_ID}
      - OAUTH2_CLIENT_SECRET=${OAUTH2_CLIENT_SECRET}
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
  grafana_data:
  gradle_home:
  app_home:
