global:
  scrape_interval: 15s # 스크랩 주기
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ubuntu-api-1"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["meettify.store:8080"] # 환경 변수로 변경

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
