global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ubuntu-api-1"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8080"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus 엔드포인트

  - job_name: "grafana"
    static_configs:
      - targets: ["localhost:3000"] # Grafana 메트릭 수집
