global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "meettify"
    metrics_path: "/monitor/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets:
        - "host.docker.internal:8080"

  - job_name: "prometheus"
    static_configs:
      - targets:
        - "host.docker.internal:9090"

