spring:
  profiles:
    group:
      local:
        - jwt
        - oauth2
        - local
        - s3
        - local
        - mail
      prod:
        - prod
    active: prod
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true