name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Run Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew wrapper
          ./gradlew clean build


      - name: Install Docker
        run: |
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Installing..."
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          else
            echo "Docker is already installed."
          fi

      # 도커 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 프로젝트 빌드 그리고 이미지처리
      - name: Build and push Docker image with Jib
        run: ./gradlew jib --image=${{ secrets.DOCKERHUB_REPOSITORY }}/meettify:latest
        env:
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
          RDS_MYSQL_SECRET: ${{ secrets.RDS_MYSQL_SECRET }}
          RDS_MYSQL_NAME: ${{ secrets.RDS_MYSQL_NAME }}
          RDS_MYSQL_URL: ${{ secrets.RDS_MYSQL_URL }}
          S3_ACCESS: ${{ secrets.S3_ACCESS }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          GOOGLE_CLIENT: ${{ secrets.GOOGLE_CLIENT }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          NAVER_CLIENT: ${{ secrets.NAVER_CLIENT }}
          NAVER_SECRET: ${{ secrets.NAVER_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      # ec2 연결
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d
            # 환경 변수를 직접 설정하여 실행
            export AWS_ACCESS_KEY_ID=${{ secrets.S3_ACCESS }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET }}
            export OAUTH2_CLIENT_ID=${{ secrets.GOOGLE_CLIENT }}
            export OAUTH2_CLIENT_SECRET=${{ secrets.GOOGLE_SECRET }}
            export OAUTH2_NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT }}
            export OAUTH2_NAVER_CLIENT_SECRET=${{ secrets.NAVER_SECRET }}
            export RDS_MYSQL_URL=${{ secrets.RDS_MYSQL_URL }}
            export RDS_MYSQL_NAME=${{ secrets.RDS_MYSQL_NAME }}
            export RDS_MYSQL_SECRET=${{ secrets.RDS_MYSQL_SECRET }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            docker-compose up -d
