name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # Specify the JDK distribution (temurin, zulu, etc.)

      - name: Install Docker  # Docker 및 Docker Compose 설치 추가
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io containerd
          sudo apt-get install -y containerd.io


      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d

      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Wait for services to be healthy
        run: |
          docker-compose -f docker-compose.yml ps
          sleep 20

      - name: Run Gradle Build
        run: ./gradlew clean build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml run --rm api-server ./run-tests.sh

      - name: Clean up
        run: |
          docker-compose -f docker-compose.yml down
